apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-script
data:
  backup.sh: |
    #!/bin/bash
    set -ex
    apt update
    apt install wget
    sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
    sleep 5
    apt update
    apt install -y postgresql-client
    cp /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
    echo "Asia/Kolkata" > /etc/timezone
    backup_filename="pgbackup_"$(date +"%d.%m.%y-%H-%M-%S")
    echo -e "\nBacking Up ..."
    pg_dumpall -h ${PG_HOST} -p ${PG_PORT} -U ${PG_ADMIN_USER} -f ${backup_filename}
    if [[ $? != 0 ]]
    then
        echo "Exiting......"
        exit
    fi
    sleep 10
    echo -e "\nFinished Backup"
    tar -czf ${backup_filename}".tar.gz" ${backup_filename}
    gcloud config set project ${GCLOUD_PROJECT}
    if [[ ! -z $GOOGLE_APPLICATION_CREDENTIALS ]]
    then
        gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
    fi
    gsutil cp ${backup_filename}".tar.gz" gs://${BUCKET_NAME}
    sleep 10
    if [[ ! -z $GOOGLE_APPLICATION_CREDENTIALS ]]
    then
    gcloud auth revoke
    fi